# Generated by Django 3.2.2 on 2021-12-27 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getColumns', '0002_auto_20211227_1239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='t_datasource_config',
            options={},
        ),
        migrations.AlterModelTable(
            name='t_datasource_config',
            table=None,
        ),
    ]
