# Generated by Django 3.2.2 on 2021-12-14 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAPIs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
    ]
