# Generated by Django 3.2.2 on 2021-12-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPIs', '0002_remove_address_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
