# Generated by Django 3.2.2 on 2021-12-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPIs', '0003_address_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
