# Generated by Django 3.2.2 on 2021-12-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPIs', '0006_auto_20211217_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name1',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pas',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
