# Generated by Django 3.2.2 on 2021-12-17 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userAPIs', '0007_auto_20211217_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirmpassword',
        ),
    ]
