# Generated by Django 3.2.2 on 2021-12-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAPIs', '0008_remove_user_confirmpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='app_role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=255)),
                ('role_mapping', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='company',
            new_name='f_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='l_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
